# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x12\x0c\x63o2analytics\"(\n\x10UploadCSVRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"4\n\x11UploadCSVResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"!\n\rGetCSVRequest\x12\x10\n\x08\x63sv_name\x18\x01 \x01(\t\"o\n\tCSVRecord\x12\x33\n\x06\x66ields\x18\x01 \x03(\x0b\x32#.co2analytics.CSVRecord.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\":\n\x0eGetCSVResponse\x12(\n\x07records\x18\x01 \x03(\x0b\x32\x17.co2analytics.CSVRecord\"\xb4\x02\n\x0bGlobalInput\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x13\n\x0b\x66\x61\x63ility_id\x18\x02 \x01(\t\x12\x15\n\rfacility_name\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\x19\n\x11storage_site_type\x18\x06 \x01(\t\x12\x1a\n\x12\x63o2_emitted_tonnes\x18\x07 \x01(\x01\x12\x1b\n\x13\x63o2_captured_tonnes\x18\x08 \x01(\x01\x12\x19\n\x11\x63o2_stored_tonnes\x18\t \x01(\x01\x12\"\n\x1a\x63\x61pture_efficiency_percent\x18\n \x01(\x01\x12!\n\x19storage_integrity_percent\x18\x0b \x01(\x01\x12\x14\n\x0c\x61nomaly_flag\x18\x0c \x01(\x08\"J\n\x11UpdateCSVResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61nomaly_flag\x18\x03 \x01(\x08\"<\n\x12GetInsightsRequest\x12\x15\n\rfacility_name\x18\x01 \x01(\t\x12\x0f\n\x07scatter\x18\x02 \x01(\x08\"*\n\x13GetInsightsResponse\x12\x13\n\x0bplot_base64\x18\x01 \x01(\t2\xc9\x02\n\x13\x43O2AnalyticsService\x12L\n\tUploadCSV\x12\x1e.co2analytics.UploadCSVRequest\x1a\x1f.co2analytics.UploadCSVResponse\x12\x43\n\x06GetCSV\x12\x1b.co2analytics.GetCSVRequest\x1a\x1c.co2analytics.GetCSVResponse\x12G\n\tUpdateCSV\x12\x19.co2analytics.GlobalInput\x1a\x1f.co2analytics.UpdateCSVResponse\x12V\n\x0fGetInsightsPlot\x12 .co2analytics.GetInsightsRequest\x1a!.co2analytics.GetInsightsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSVRECORD_FIELDSENTRY']._loaded_options = None
  _globals['_CSVRECORD_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_UPLOADCSVREQUEST']._serialized_start=38
  _globals['_UPLOADCSVREQUEST']._serialized_end=78
  _globals['_UPLOADCSVRESPONSE']._serialized_start=80
  _globals['_UPLOADCSVRESPONSE']._serialized_end=132
  _globals['_EMPTY']._serialized_start=134
  _globals['_EMPTY']._serialized_end=141
  _globals['_GETCSVREQUEST']._serialized_start=143
  _globals['_GETCSVREQUEST']._serialized_end=176
  _globals['_CSVRECORD']._serialized_start=178
  _globals['_CSVRECORD']._serialized_end=289
  _globals['_CSVRECORD_FIELDSENTRY']._serialized_start=244
  _globals['_CSVRECORD_FIELDSENTRY']._serialized_end=289
  _globals['_GETCSVRESPONSE']._serialized_start=291
  _globals['_GETCSVRESPONSE']._serialized_end=349
  _globals['_GLOBALINPUT']._serialized_start=352
  _globals['_GLOBALINPUT']._serialized_end=660
  _globals['_UPDATECSVRESPONSE']._serialized_start=662
  _globals['_UPDATECSVRESPONSE']._serialized_end=736
  _globals['_GETINSIGHTSREQUEST']._serialized_start=738
  _globals['_GETINSIGHTSREQUEST']._serialized_end=798
  _globals['_GETINSIGHTSRESPONSE']._serialized_start=800
  _globals['_GETINSIGHTSRESPONSE']._serialized_end=842
  _globals['_CO2ANALYTICSSERVICE']._serialized_start=845
  _globals['_CO2ANALYTICSSERVICE']._serialized_end=1174
# @@protoc_insertion_point(module_scope)
